FROM node:12-alpine

# Allow node modules to be called directly
ENV PATH $PATH:/client/node_modules/.bin

# Build client
RUN apk add --no-cache python3 && ln -sf python3 /usr/bin/python
RUN apk add --no-cache git g++ make

WORKDIR /client
COPY package*.json ./

RUN npm set progress=false && npm ci --no-cache

# Run dev client
EXPOSE 4000
CMD [ "npm", "run", "start" ]
