version: '3.7'

services:
  client:
    image: ${PROJECT}-client
    container_name: ${PROJECT}-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./client:/client # Use client dir in host for hot reloading
      - /client/node_modules # Use node_modules in container
    depends_on:
      - server
    networks:
      - ets-dev

  server:
    image: ${PROJECT}-server
    container_name: ${PROJECT}-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        VERSION: ${COMMIT_SHA}
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - VERSION=${COMMIT_SHA}
    ports:
      - "80:80"
      - "9229:9229"
    volumes:
      - ./server:/server # Use server dir in host for hot reloading
      - /server/node_modules # Use node_modules in container
    depends_on:
      - mongodb
    networks:
      - ets-dev
  
  ### Lambda Function #############################
  lambda-phacToSbc:
    container_name: ${PROJECT}-lambda-phacToSbc
    image: lambci/lambda:nodejs12.x
    ports:
      - "9001:9001"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AWS_DEFAULT_REGION=ca-central-1
      - DOCKER_LAMBDA_WATCH=1
      - DOCKER_LAMBDA_STAY_OPEN=1
    depends_on:
      - mongodb
    volumes:
      - ./server/lambda/layer/common:/opt:ro,delegated
      - ./server/lambda/phacToSbc:/var/task:ro,delegated
    command: index.handler
    networks:
      - frontend

  ### Lambda Function #############################
  lambda-etsToSbc:
    container_name: ${PROJECT}-lambda-etsToSbc
    image: lambci/lambda:nodejs12.x
    expose:
      - "9002"
    ports:
      - "9002:9001"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AWS_DEFAULT_REGION=ca-central-1
      - DOCKER_LAMBDA_WATCH=1
      - DOCKER_LAMBDA_STAY_OPEN=1
    depends_on:
      - mongodb
    volumes:
      - ./server/lambda/layer/common:/opt:ro,delegated
      - ./server/lambda/etsToSbc:/var/task:ro,delegated
    command: index.handler
    networks:
      - ets-dev

  mongodb:
    container_name: ${PROJECT}-mongodb
    image: mongo:3.6-xenial
    restart: always
    ports:
        - ${DB_PORT}:${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./.docker/mongo/databaseInit:/docker-entrypoint-initdb.d
      - ets-mongo-data-configdb:/data/configdb
      - ets-mongo-data-db:/data/db
    networks:
      - ets-dev

networks:
  ets-dev:
    driver: "bridge"

volumes:
    ets-mongo-data-configdb:
    ets-mongo-data-db:
