global:
  application_name: enhanced-travel-screening
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application