openapi: 3.0.1
info:
  title: Enhanced Traveller Screening
  description: Spec for BC Enhanced Traveller Screening API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://travelscreening.gov.bc.ca/api/v1
paths:
  /phac/submission:
    post:
      summary: Submission from PHAC, secured by JWT for PHAC users only
      security:
        - bearerAuth: []
      requestBody:
        description: Form data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Phac'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhacResponse'
        400:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhacValidationError'
  /login:
    post:
      summary: Login using username and password, receive JWT
      requestBody:
        description: Login data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /form:
    post:
      summary: Submit a new form on behalf of a traveller
      requestBody:
        description: Form data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Form'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormResponse'
  /form/{id}:
    patch:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the traveller's form
      summary: Edit existing form with determination and notes
      security:
        - bearerAuth: []
      requestBody:
        description: Determination data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Determination'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeterminationResponse'
  /last-name/{lname}:
    get:
      parameters:
        - in: path
          name: lname
          schema:
            type: string
          required: true
          description: Traveller's last name (partial match)
      summary: Get travellers by last name (partial match)
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormsResponse'
  /validate:
    get:
      summary: Validate JWT
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK
  /version:
    get:
      summary: Version hash
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Determination:
      required:
        - determination
        - notes
      properties:
        determination:
          type: string
        notes:
          type: string
    DeterminationResponse:
      type: object
      properties:
        id:
          type: string
    VersionResponse:
      type: object
      properties:
        version:
          type: string
    FormsResponse:
      type: object
      properties:
        travellers:
          type: array
          items:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              telephone:
                type: string
              email:
                type: string
              address:
                type: string
              city:
                type: string
              province:
                type: string
              postalCode:
                type: string
              dob:
                type: string
              includeAdditionalTravellers:
                type: boolean
              additionalTravellers:
                type: array
                items:
                  type: object
                  properties:
                    firstName:
                      type: string
                    lastName:
                      type: string
                    dob:
                      type: string
              arrival:
                type: object
                properties:
                  date:
                    type: string
                  by:
                    type: string
                  from:
                    type: string
                  flight:
                    type: string
              accomodations:
                type: boolean
              isolationPlan:
                type: object
                properties:
                  city:
                    type: string
                  address:
                    type: string
                  type:
                    type: string
              supplies:
                type: boolean
              ableToIsolate:
                type: boolean
              transportation:
                type: array
                items:
                  type: string
              certified:
                type: boolean
    Form:
      required:
        - ableToIsolate
        - accomodations
        - additionalTravellers
        - address
        - arrival
        - certified
        - city
        - dob
        - firstName
        - includeAdditionalTravellers
        - isolationPlan
        - lastName
        - province
        - supplies
        - telephone
        - transportation
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        telephone:
          type: string
        email:
          type: string
          pattern: ^.+@.+\..+$
        address:
          type: string
        city:
          type: string
        province:
          type: string
          enum:
            - Alberta
            - British Columbia
            - Manitoba
            - New Brunswick
            - Newfoundland and Labrador
            - Nova Scotia
            - Ontario
            - Prince Edward Island
            - Québec
            - Saskatchewan
            - Nunavut
            - Northwest Territories
            - Yukon
            - Other
        postalCode:
          type: string
        dob:
          type: string
          format: date
          pattern: ^\d{4}\/\d{2}\/\d{2}$
        includeAdditionalTravellers:
          type: boolean
        additionalTravellers:
          type: array
          description: Must be empty if includeAdditionalTravellers is false
          minItems: 0
          maxItems: 10
          items:
            type: object
            required:
              - dob
              - firstName
              - lastName
            properties:
              firstName:
                type: string
              lastName:
                type: string
              dob:
                type: string
                format: date
                pattern: ^\d{4}\/\d{2}\/\d{2}$
        arrival:
          type: object
          required:
            - by
            - date
            - from
          properties:
            date:
              type: string
              format: date
              pattern: ^\d{4}\/\d{2}\/\d{2}$
            by:
              type: string
            from:
              type: string
            flight:
              type: string
        accomodations:
          type: boolean
        isolationPlan:
          type: object
          description: Must be null if accomodations is false
          nullable: true
          required:
            - address
            - city
            - type
          properties:
            city:
              type: string
            address:
              type: string
            type:
              type: string
        supplies:
          type: boolean
        ableToIsolate:
          type: boolean
        transportation:
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
              - taxi
              - personal
              - public
        certified:
          type: boolean
    FormResponse:
      type: object
      properties:
        id:
          type: string
        isolationPlanStatus:
          type: boolean
    Login:
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    Phac:
      required:
        - covid_id
      properties:
        covid_id:
          type: string
      additionalProperties:
        anyOf:
          - type: string
          - type: number
          - type: integer
          - type: boolean
          - type: array
            items: {}
          - type: object
        nullable: false
    PhacResponse:
      type: object
      properties:
        successful:
          type: object
        duplicates:
          type: array
          items:
            type: string
        errors:
          type: array
          items:
            type: string
    PhacValidationError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              index:
                type: string
              errors:
                type: array
                items:
                  type: string
