openapi: 3.0.1
info:
  title: Enhanced Traveller Screening
  description: Spec for BC Enhanced Traveller Screening API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://travelscreening.gov.bc.ca/api/v1
paths:
  /phac/submission:
    post:
      summary: Submission from PHAC, secured by JWT for PHAC users only
      requestBody:
        description: Form data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Phac'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhacResponse'
        400:
          description: Invalid input
components:
  schemas:
    Phac:
      required:
      - covid_id
      properties:
        covid_id:
          type: string
      additionalProperties:
        anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
        nullable: false
    PhacResponse:
      type: object
      properties:
        successful:
          type: object
        duplicates:
          type: array
          items:
            type: string
        errors:
          type: array
          items:
            type: string