openapi: 3.0.1
info:
  title: Enhanced Traveller Screening
  description: Spec for BC Enhanced Traveller Screening API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://travelscreening.gov.bc.ca/api/v1
paths:
  /form:
    post:
      summary: Submit a new form on behalf of a traveller
      requestBody:
        description: Form data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Form'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        400:
          description: Invalid input
components:
  schemas:
    Form:
      required:
      - ableToIsolate
      - accomodations
      - additionalTravellers
      - address
      - arrival
      - certified
      - city
      - dob
      - firstName
      - includeAdditionalTravellers
      - isolationPlan
      - lastName
      - province
      - supplies
      - telephone
      - transportation
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        telephone:
          type: string
        email:
          type: string
          pattern: ^.+@.+\..+$
        address:
          type: string
        city:
          type: string
        province:
          type: string
          enum:
          - Alberta
          - British Columbia
          - Manitoba
          - New Brunswick
          - Newfoundland and Labrador
          - Nova Scotia
          - Ontario
          - Prince Edward Island
          - Québec
          - Saskatchewan
          - Nunavut
          - Northwest Territories
          - Yukon
          - Other
        postalCode:
          type: string
        dob:
          type: string
          format: date
          pattern: ^\d{4}\/\d{2}\/\d{2}$
        includeAdditionalTravellers:
          type: boolean
        additionalTravellers:
          type: array
          description: Must be empty if includeAdditionalTravellers is false
          minItems: 0
          maxItems: 10
          items:
            type: object
            required:
            - dob
            - firstName
            - lastName
            properties:
              firstName:
                type: string
              lastName:
                type: string
              dob:
                type: string
                format: date
                pattern: ^\d{4}\/\d{2}\/\d{2}$
        arrival:
          type: object
          required:
          - by
          - date
          - from
          properties:
            date:
              type: string
              format: date
              pattern: ^\d{4}\/\d{2}\/\d{2}$
            by:
              type: string
            from:
              type: string
            flight:
              type: string
        accomodations:
          type: boolean
        isolationPlan:
          type: object
          description: Must be null if accomodations is false
          nullable: true
          required:
          - address
          - city
          - type
          properties:
            city:
              type: string
            address:
              type: string
            type:
              type: string
        supplies:
          type: boolean
        ableToIsolate:
          type: boolean
        transportation:
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
            - taxi
            - personal
            - public
        certified:
          type: boolean
    Response:
      type: object
      properties:
        id:
          type: string
        isolationPlanStatus:
          type: boolean
