name: Build and Deploy

on:
  push:
    tags:
      - dev

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  PROJECT: ${{ secrets.PROJECT }}
  REGION: ${{ secrets.REGION }}
  DEV_URL: ${{ secrets.DEV_URL }}

jobs:
  audit:
    name: Run NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Audit
        run: |
          cd "$GITHUB_WORKSPACE/client" && npm audit --audit-level=moderate --production
          cd "$GITHUB_WORKSPACE/server" && npm audit --audit-level=moderate
          cd "$GITHUB_WORKSPACE"

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Add Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Extract Tag, Set Source and Destination Env
        run: |
          export ENV_SUFFIX=${GITHUB_REF#refs/*/}
          echo "ENV_SUFFIX=$ENV_SUFFIX" >> $GITHUB_ENV
          echo "DESTINATION_ENV=$(make get-latest-env-name -f makefile.old)" >> $GITHUB_ENV

      - name: Build Image
        run: make build-image -f makefile.old

      - name: Push Image
        run: make push-image -f makefile.old

      - name: Create Artifact and Deploy to EB
        run: make promote-image -f makefile.old

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: ${{ env.DEV_URL }}
          cmd_options: '-I'
