name: Test application (e2e)

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run NPM Test (e2e)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [3.6]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint
        working-directory: ./server
        run: |
          npm install
          npm run lint

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: NPM Test
        working-directory: ./server
        env:
          USE_GHA_MONGO: 'true'
        run: |
          npm ci
          npm test
