name: Build & Deploy (Prod)

on:
  push:
    tags:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: prod
    env:
      ENV_NAME: prod
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Tag to PROD"
          SLACK_MESSAGE: "Starting Deployment :deployparrot:"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.CI_SA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_SA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
          role-to-assume: arn:aws:iam::026615665612:role/PBMMOps-BCGOV_prod_Project_Role_CI_Role
          role-duration-seconds: 1200
          role-session-name: ci-deployment

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "v1.0.0"
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Build Server
        run: make build-lambdas

      - name: Terraform Init
        run: make init

      - name: Terraform Apply
        run: make apply

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Tag to PROD"
          SLACK_MESSAGE: "Deployment Completed :rocket:"
