name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.CI_SA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_SA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
          role-to-assume: arn:aws:iam::026615665612:role/PBMMOps-BCGOV_prod_Project_Role_CI_Role
          role-duration-seconds: 1200
          role-session-name: ci-deployment

      # - name: Build Client
      #   run: make build-client

      # - name: Deploy
      #   run: aws s3 sync ./terraform/build/client s3://ets-app-prod --delete && aws --region ca-central-1 cloudfront create-invalidation --distribution-id E2X1WI7YGUJ0M2 --paths "/*"

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "v1.0.0"
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Build Server
        run: make build-lambdas
        env:
          ENV_NAME: ${{ steps.extract_branch.outputs.branch }}

      - name: Terraform Init
        run: make init
        env:
          ENV_NAME: ${{ steps.extract_branch.outputs.branch }}

      - name: Terraform Apply
        run: make apply
        env:
          ENV_NAME: ${{ steps.extract_branch.outputs.branch }}