name: Deploy Lambda Function

on:
  push:
    tags:
      - phactosbc-lambda-prod

env:
  REGION: ca-central-1
  LAMBDA_FUNC: phacToSbc
  LAMBDA_LAYER: common

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Zip common layer and ship to AWS Lambda
        working-directory: ./server/lambda/layer/common
        run: |
          npm install
          zip -r lambdaLayer.zip .
          echo ::set-env name=LAYER_ARN::$(aws lambda publish-layer-version --compatible-runtimes nodejs12.x --layer-name ${{ env.LAMBDA_LAYER }} --zip-file fileb://${PWD}/lambdaLayer.zip | jq '.LayerVersionArn' -r)

      - name: Zip lambda folder and ship to AWS Lambda
        working-directory: ./server/lambda/phacToSbc
        run: |
          echo ${GITHUB_SHA} > commit_hash.txt
          zip -r lambdaFunc.zip .
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNC }} --zip-file fileb://${PWD}/lambdaFunc.zip | tail -n 0
          aws lambda update-function-configuration --function-name ${{ env.LAMBDA_FUNC }} --layers $(LAYER_ARN)



