name: Blue Green Image Promotion

on:
  push:
    tags:
      - staging
      - prod

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  PROJECT: ${{ secrets.PROJECT }}
  REGION: ${{ secrets.REGION }}

jobs:
  promote:
    name: Blue Green Image Promotion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Add Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Extract Tag, Set Source and Destination Env
        run: |
          export ENV_SUFFIX=${GITHUB_REF#refs/*/}
          echo "ENV_SUFFIX=$ENV_SUFFIX" >> $GITHUB_ENV
          echo "SOURCE_ENV=$(make get-latest-env-name -f makefile.old)" >> $GITHUB_ENV
          echo "DESTINATION_ENV=$(make create-new-env-name -f makefile.old)" >> $GITHUB_ENV

      - name: Validate Image
        run: make validate-image -f makefile.old

      - name: Clone EB Enviroment
        run: |
          pip install awsebcli
          eb clone ${{ env.SOURCE_ENV }} --clone_name ${{ env.DESTINATION_ENV }} --exact --verbose

      - name: Secure New Load Balancer
        run: |
          export ENV_LOAD_BALANCER=$(make get-dest-env-load-balancer-name -f makefile.old)
          make create-secure-tls-policy -f makefile.old
          make set-secure-tls-policy -f makefile.old

      - name: Create Artifact and Deploy to EB
        run: make promote-image -f makefile.old
