name: NPM Audit Test

on:
  push:
    branches:
      - npm-audit

      
jobs:
  audit:
    name: NPM Audit
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Audit
        run: |
          cd "$GITHUB_WORKSPACE/client" && npm audit
          cd "$GITHUB_WORKSPACE/server" && npm audit
          cd "$GITHUB_WORKSPACE"
