name: Test application (e2e)

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run NPM Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH to the dev database
        run: |
          echo ${{ secrets.ETS_BASTION_HOST_KEY }} > ets-bastion-host.pem
          ssh -i ets-bastion-host.pem -L ${{ secrets.DB_PORT }}:${{ secrets.DB_REMOTE_SERVER }}:${{ secrets.DB_PORT }} ec2-user@${{ secrets.ETS_BASTION_HOST }} -N &

      - name: NPM Test
        working-directory: ./server
        run: |
          npm install
          npm test

